image: node:18
pipelines:
  default:
    - step:
        name: Run Postman tests
        caches:
          - node
        script:
          - npm install -g newman
          - newman run postman/collection.postman_collection.json --env-var baseUrl=https://api.demo.com
